[phases.setup]
nixPkgs = ["nodejs_20", "npm", "ffmpeg", "python3"]

[phases.install]
cmds = ["NODE_OPTIONS='--max-old-space-size=4096' npm install"]

[start]
cmd = "NODE_OPTIONS='--max-old-space-size=2048' npm start"
